import { Observable } from 'rxjs';
import { Injectable } from '@angular/core';
import { ProductsApi } from './api/products.api';
import { ItemsState } from './state/items.state';
import { Product } from './models/product';
import { tap } from 'rxjs/operators';

@Injectable()
export class ItemsFacade {

  constructor(
    private ProductApi: ProductsApi,
    private itemsState: ItemsState) { }

  isUpdating$(): Observable<boolean> {
    return this.itemsState.isUpdating$();
  }

  getProducts$(): Observable<Product[]> {
    // here we just pass the state without any projections
    // it may happen that it is necessary to combine two or more streams and expose to the components
    return this.itemsState.getProducts$();
  }

  loadProducts() {
    return this.ProductApi.getProducts()
      .pipe(
        tap(p => this.itemsState.setProducts(p))
      );
  }

  // optimistic update
  // 1. update UI state
  // 2. call API
  addProduct(category: Product) {
    this.itemsState.addProduct(category);
    this.ProductApi.createProduct(category)
      .subscribe(
        (addedCategoryWithId: Product) => {
          // success callback - we have id generated by the server, let's update the state
          this.itemsState.updateProductId(category, addedCategoryWithId)
        },
        (error: any) => {
          // error callback - we need to rollback the state change
          this.itemsState.removeProduct(category);
          console.log(error);
        }
      );
  }

  // pessimistic update
  // 1. call API
  // 2. update UI state
  updateProduct(category: Product) {
    this.itemsState.setUpdating(true);
    this.ProductApi.updateProduct(category)
      .subscribe(
        () => this.itemsState.updateProduct(category),
        (error) => console.log(error),
        () => this.itemsState.setUpdating(false)
      );
  }
}